### ISSUE TITLE
missing deps in the pip package

### ISSUE THREAD

**Issue by mikkokotila** [ashim888/awis#6]
bs4 and requests are missing. Giving that the module only runs when these are present, maybe better to include it to setup.py. If you like I can make a PR with this change.

**Comment by mikkokotila** [comment]
also lxml. So all in three: 

pip install requests
pip install bs4
pip install lxml

**Comment by ashim888** [comment]
@mikkokotila done but make sure you have these two libxml2-dev and libxslt-dev :+1:
